config/routes.rb
Rails.application.routes.draw do
  resources :planets
  root "planets#index"
end

app/models/planet.rb
class Planet < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController

  def index
    @planets = Planet.all
  end

  def new
    @planet = Planet.new
  end

  def create
    planet_params = params.require(:planet).permit(:name, :date, :location, :description, :life_forms)
    @planet = Planet.new(planet_params)
    @planet.save
    redirect_to planets_path
  end

  def show
      @planet = Planet.find(params[:id])
  end

  def edit
      @planet = Planet.find(params[:id])
  end

  def update
    planet_params = params.require(:planet).permit(:name, :date, :location, :description, :life_forms)
      @planet = Planet.find(params[:id])
      @planet.update(planet_params)
      redirect_to planet_path(@planet)
  end

  def destroy
    @planet = Planet.find(params[:id])
    @planet.destroy
    redirect_to planets_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UniversePlanets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/planets/edit.html.erb
<h1>Edit Planet</h1>
<%= form_for @planet do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :date_visiting %>
<%= f.date_field :date %>

<%= f.label :location %>
<%= f.text_field :location %>

<%= f.label :description_of_your_journey %>
<%= f.text_field :description %>

<%= f.label :hosting_other_life_forms? %>
<%= f.check_box :life_forms %>

<%= f.submit %>
<% end %>

app/views/planets/index.html.erb
<h1>The Universe</h1>
<p><%= link_to "Plan your intergalactic stellar times!", new_planet_path %></p>
<table>
  <thead>
    <tr>
        <th>Name</th>
        <th>Date</th>
        <th>Location</th>
        <th>Description</th>
        <th>Life forms?</th>
    </tr>
  </thead>
    <tbody>
      <% @planets.each do |planet| %>
      <tr>
        <td><%= planet.name %></td>
        <td><%= planet.date %></td>
        <td><%= planet.location %></td>
        <td><%= planet.description %></td>
        <td><%= planet.life_forms %></td>
        <td><%= link_to "Edit", edit_planet_path(planet) %></td>
        <td><%= link_to "Show", planet_path(planet) %></td>
        <td><%= link_to "Delete", planet_path(planet), method: :delete %></td>
      </tr>
      <% end %>
    </tbody>
 </table>

app/views/planets/new.html.erb
<h1>Planet Portal</h1>
<%= form_for @planet do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :date_visiting %>
  <%= f.date_field :date %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.label :description_of_your_journey %>
  <%= f.text_field :description %>

  <%= f.label :hosting_other_life_forms? %>
  <%= f.check_box :life_forms %>

<%= f.submit "Transcend" %>
<% end %>

app/views/planets/show.html.erb
<h1><%= @planet.name %></h1>
<%= @planet.date %></br>
<%= @planet.location %></br>
<%= @planet.description %></br>
<%= @planet.life_forms %></br>

<%= link_to "All Planets", planets_path %> |
<%= link_to "Edit", edit_planet_path(@planet) %>